#!/usr/bin/env bash
# Regenerates contextGIST's third-party licence disclosure from Cargo.lock:
#
#   docs/THIRD-PARTY.md                        — human-readable table
#   apps/macos/Resources/ThirdPartyNotices.txt — plain-text copy bundled into
#                                                contextGIST.app (and the DMG)
#
# Covers every external crate reachable from contextgist-ffi via normal
# (non-dev, non-build) dependency edges — `cargo tree -p contextgist-ffi -e
# normal` — which is everything statically linked into the app. Path/workspace
# crates (contextgist-ffi itself and GIST's gist-* crates) are excluded as
# first-party. Mirrors GIST's docs/THIRD-PARTY.md methodology (reader commit
# 401a972).
#
# Re-run after any Cargo.lock change, including upstream ~/develop/reader
# changes that alter gist-model/gist-parse-txt/gist-rsvp's dependencies.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/contextgist-third-party.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

cargo tree -p contextgist-ffi -e normal --prefix none --format '{p}' \
    | sed 's/ (.*)//' | sort -u > "$TMP_DIR/tree.txt"
cargo metadata --format-version 1 > "$TMP_DIR/meta.json"

python3 - "$TMP_DIR" "$REPO_ROOT" <<'PY'
import datetime, json, sys

tmp, root = sys.argv[1], sys.argv[2]
meta = json.load(open(f"{tmp}/meta.json"))
packages = {(p["name"], p["version"]): p for p in meta["packages"]}

rows = []
for line in open(f"{tmp}/tree.txt"):
    name, ver = line.split()[:2]
    p = packages[(name, ver.lstrip("v"))]
    if p["source"] is None:  # workspace/path crate: first-party
        continue
    rows.append((p["name"], p["version"], p.get("license") or "UNKNOWN",
                 p.get("repository") or ""))
rows.sort()
unknown = [r for r in rows if r[2] == "UNKNOWN"]
if unknown:
    sys.exit(f"error: no declared licence for {unknown}; resolve manually")

today = datetime.date.today().isoformat()
n = len(rows)

md = [
    "# Third-party dependencies",
    "",
    "contextGIST itself is MIT-licensed (see `LICENSE`). Its Rust core",
    "(`crates/contextgist-ffi`, statically linked into `contextGIST.app`) reuses",
    "GIST's `gist-model`/`gist-parse-txt`/`gist-rsvp` crates (MIT, same author,",
    "via path dependency) and depends on the external crates below. The macOS",
    "app has no other third-party dependencies: no Swift packages, no CocoaPods,",
    "no vendored SDKs.",
    "",
    "**Generated by `tools/gen-third-party.sh`. Do not edit by hand.** The same",
    "list ships inside the app as `Contents/Resources/ThirdPartyNotices.txt`.",
    "",
    "**Methodology:**",
    f"- Regenerated {today} from `Cargo.lock`: every crate reachable from",
    "  `contextgist-ffi` via `cargo tree -e normal`, deduplicated, with each",
    "  crate's declared licence from `cargo metadata`. "
    f"{n} external crates.",
    "- uniffi's proc-macro crates only run at compile time and aren't part of",
    "  the shipped machine code; they're listed anyway for completeness.",
    "- Checked against GIST's licence allow-list: `cargo deny --exclude-dev",
    "  check licenses bans sources --config ~/develop/reader/deny.toml` →",
    "  `bans ok, licenses ok, sources ok`.",
    "- **MPL-2.0 (uniffi):** file-level copyleft. contextGIST uses uniffi",
    "  unmodified, so the obligation is to tell recipients where its source is",
    "  (the repository links below). Modifying uniffi's own files would",
    "  require publishing those modified files under MPL-2.0.",
    "",
    "| Crate | Version | Licence | Repository |",
    "|---|---|---|---|",
]
md += [f"| {a} | {b} | {c} | <{d}> |" if d else f"| {a} | {b} | {c} | |"
       for a, b, c, d in rows]
open(f"{root}/docs/THIRD-PARTY.md", "w").write("\n".join(md) + "\n")

txt = [
    "contextGIST — Third-Party Notices",
    "=================================",
    "",
    "contextGIST is licensed under the MIT License.",
    "",
    "Its Rust core (statically linked into this app; there are no other",
    "third-party dependencies) depends on the following third-party Rust",
    "crates. The source code of each is available at the repository listed.",
    "",
    f"Rust dependencies ({n} crates)",
    "-" * len(f"Rust dependencies ({n} crates)"),
    "",
]
for a, b, c, d in rows:
    txt.append(f"{a} {b} -- {c}")
    if d:
        txt.append(f"  {d}")
    txt.append("")
open(f"{root}/apps/macos/Resources/ThirdPartyNotices.txt", "w").write("\n".join(txt))
print(f"✓ {n} crates written to docs/THIRD-PARTY.md and "
      "apps/macos/Resources/ThirdPartyNotices.txt")
PY
